checks:
    php: true

build:
    environment:
        php:
            version: '7.3'
            ini:
                'date.timezone': 'UTC'

filter:
    paths:
        - src/*
    excluded_paths:
       - vendor/*
       - tests/*

before_commands:
    - "composer install --prefer-dist"
