language: php

sudo: false

php:
  - 7.3
  - 7.4
  - 8.0

matrix:
  fast_finish: true

before_script:
  - composer self-update

install:
  - composer install --dev --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpcs ./ -p --encoding=utf-8 --extensions=php --ignore=vendor --ignore=tests --standard=phpcs.xml
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml
  - ./vendor/bin/phpstan analyse -l 8 --no-progress -c phpstan.neon ./

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $COMPOSER_CACHE_DIR

notifications:
  email:
    - genvaldartem@gmail.com
